---
services:
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gametime
