name: ci_checks

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          packages: python312Packages.openapi-spec-validator

      # Validate OpenAPI schema
      - run: openapi-spec-validator openapi.yml

      # Run whole project's formatting, and validate nothing changed
      - run: nix fmt
      - name: Get all changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      - name: Fail if any changes
        if: steps.changed-files-yaml.outputs.any_changed == 'true'  
        run: |
          echo "Formatter changed files! Please run the formatter before committing. 'nix fmt'"
          exit 1

      # If we want to enable testing
      # - uses: erlef/setup-beam@v1
      #   with:
      #     otp-version: "27.1.2"
      #     gleam-version: "1.9.1"
      #     rebar3-version: "3"
      #     # elixir-version: "1"
      # - run: gleam deps download
      # - run: gleam test
      # - run: gleam format --check src test
