name: ci_checks

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: workflow/nix-shell-action@v3
        with:
          packages: python312Packages.openapi-spec-validator
          script: |
            openapi-spec-validator openapi.yml

      # If we want to enable testing
      # - uses: erlef/setup-beam@v1
      #   with:
      #     otp-version: "27.1.2"
      #     gleam-version: "1.9.1"
      #     rebar3-version: "3"
      #     # elixir-version: "1"
      # - run: gleam deps download
      # - run: gleam test
      # - run: gleam format --check src test
